from ROOT import TFile,kRed,kBlue,gROOT,TCanvas,TLegend,kWhite,kGreen,kFALSE,kBlack,kViolet,kOrange
gROOT.SetBatch()

f=TFile('dust/theta_qcd.root', "READ")
f2=TFile('dust/bkg_qcd.root', "READ")
#f2=TFile('heptoptagvalhistos.root', "READ")
outfile=TFile("closure.root", "RECREATE")

zero=f.Get('had_0btag_m/Mtt')
zero2=f2.Get('BaseHistos/Mtt0')
uno=f.Get('had_1btag_m/Mtt')
uno2=f2.Get('BaseHistos/Mtt1')
due=f.Get('had_2btag_m/Mtt')
due2=f2.Get('BaseHistos/Mtt2')

outfile.cd()
zero.Rebin(2)
zero2.Rebin(2)
uno.Rebin(4)
uno2.Rebin(4)
due.Rebin(4)
due2.Rebin(4)
zero.Divide(zero2)
zero.GetYaxis().SetRangeUser(0.5,1.5)
zero.SetLineWidth(3)
zero.Write('zero')
uno.Divide(uno2)
uno.GetYaxis().SetRangeUser(0.5,1.5)
uno.SetLineWidth(3)
uno.Write('uno')
due.Divide(due2)
due.GetYaxis().SetRangeUser(0.5,1.5)
due.SetLineWidth(3)
due.Write('due')

f.Close()
f2.Close()
outfile.Close()

f=TFile('dust/theta_qcd.root', "READ")
f2=TFile('dust/bkg_qcd.root', "READ")
#f2=TFile('heptoptagvalhistos.root', "READ")
outfile=TFile("closure2.root", "RECREATE")

zero=f.Get('had_0btag_m/Mtt')
zero2=f2.Get('BaseHistos/Mtt0')
uno=f.Get('had_1btag_m/Mtt')
uno2=f2.Get('BaseHistos/Mtt1')
due=f.Get('had_2btag_m/Mtt')
due2=f2.Get('BaseHistos/Mtt2')

czero=TCanvas()
zero.SetLineWidth(3)
zero2.SetLineWidth(3)
zero.SetLineColor(kBlue)
zero2.SetLineColor(kRed)
zero.Draw()
zero2.Draw('SAME')
czero.Write('zero')

cuno=TCanvas()
uno.SetLineWidth(3)
uno2.SetLineWidth(3)
uno.SetLineColor(kBlue)
uno2.SetLineColor(kRed)
uno.Draw()
uno2.Draw('SAME')
cuno.Write('uno')

cdue=TCanvas()
due.SetLineWidth(3)
due2.SetLineWidth(3)
due.SetLineColor(kBlue)
due2.SetLineColor(kRed)
due.Draw()
due2.Draw('SAME')
cdue.Write('due')

f.Close()
f2.Close()
outfile.Close()